server:
  port:
    8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<path>.*), /${path}
            - id: cash
              uri: lb://cash
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/cash/(?<path>.*), /${path}
            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/transfer/(?<path>.*), /${path}
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:8088"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    web: debug